-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(191) NOT NULL,
    `fName` VARCHAR(100) NOT NULL,
    `lName` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `otp` INTEGER NOT NULL,
    `role` ENUM('SUBSCRIBER', 'EDITOR', 'ADMIN') NOT NULL DEFAULT 'ADMIN',
    `created` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `update` DATETIME(3) NOT NULL,

    UNIQUE INDEX `User_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
